In [12]:
import pandas as pd
data = {
    "IdProducto": [1001, 1002, 1003, 1003],
    "CantidadProducto": [30, None, 25, 25],
    "Precio": [20.5, 15.0, None, 22.5]}

df = pd.DataFrame(data)
df

   IdProducto  CantidadProducto  Precio
0        1001              30.0    20.5
1        1002               NaN    15.0
2        1003              25.0     NaN
3        1003              25.0    22.5

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IdProducto        4 non-null      int64
 1   CantidadProducto  3 non-null      float64
 2   Precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [14]:
df.isnull() #Donde esta True es porque hay un valor nulo

   IdProducto  CantidadProducto  Precio
0       False             False   False
1       False              True   False
2       False             False    True
3       False             False   False

In [15]:
df.notnull() #Donde estan los False hay un valor nulo

   IdProducto  CantidadProducto  Precio
0        True              True    True
1        True             False    True
2        True              True   False
3        True              True    True

In [19]:
df.isnull().mean()

IdProducto          0.00
CantidadProducto    0.25
Precio              0.25
dtype: float64

In [20]:
df.notnull().sum()

IdProducto          4
CantidadProducto    3
Precio              3
dtype: int64

In [21]:
#SOLUCION A LOS NULOS... NO ELIMINARLOS... QUIZA REEMPLAZARLOS DEPENDE...
# dropna.... valores no habilitados
df_eliminados = df.dropna()
df_eliminados

   IdProducto  CantidadProducto  Precio
0        1001              30.0    20.5
3        1003              25.0    22.5

In [26]:
valores_nuevos = {"CantidadProducto":0, "Precio":df["Precio"].mean()}
df_rellenados = df.fillna(valores_nuevos)
df_rellenados

   IdProducto  CantidadProducto     Precio
0        1001              30.0  20.500000
1        1002               0.0  15.000000
2        1003              25.0  19.333333
3        1003              25.0  22.500000

In [28]:
#modificar datos de una serie de dataframe
df_rellenados["CantidadProducto"] = df_rellenados["CantidadProducto"].astype(int)
df_rellenados

   IdProducto  CantidadProducto     Precio
0        1001                30  20.500000
1        1002                 0  15.000000
2        1003                25  19.333333
3        1003                25  22.500000

In [31]:
#REVISAR SI HAY DUPLICADOS... sus parametros busca que sean duplicados completos
df_unicos = df_rellenados.drop_duplicates()
df_unicos

   IdProducto  CantidadProducto     Precio
0        1001                30  20.500000
1        1002                 0  15.000000
2        1003                25  19.333333
3        1003                25  22.500000

In [32]:
#REVISAR SI HAY DUPLICADOS
df_unicos = df_rellenados.drop_duplicates(subset="IdProducto")
df_unicos

   IdProducto  CantidadProducto     Precio
0        1001                30  20.500000
1        1002                 0  15.000000
2        1003                25  19.333333