Objetivo

Realizar un análisis exploratorio de datos (EDA) sobre un conjunto de datos de medallas olímpicas utilizando Pandas. Este proyecto te permitirá aplicar los conceptos aprendidos sobre Series, DataFrames, limpieza de datos, operaciones básicas, filtrado y agregación en Pandas.

Consigna

Vas a trabajar con el conjunto de datos medallas.csv, que descargarás de la lección Proyecto del Día 6, que incluye información sobre las medallas de oro, plata, bronce y el total obtenido por cada país en los Juegos Olímpicos.

Vas a realizar una serie de tareas básicas, que te permitirán responder a las preguntas del cuestionario que encontrarás al final del día. Las tareas que realizarás son:

Cargar los Datos: Importar los datos desde el archivo CSV a un DataFrame de Pandas.
Exploración Inicial: Utilizar métodos básicos para explorar el tamaño, las columnas y los tipos de datos del DataFrame.
Limpieza de Datos: Identificar y manejar valores faltantes o incorrectos, especialmente en las columnas de medallas donde los valores faltantes indican cero medallas.
Análisis de Medallas por País: Realiza las operaciones que sean necesarias para identificar cuáles fueron los 3 países con más medallas en total. Vas a necesitar investigar los métodos de dataframe para encontrar cuál te permite ordenar los valores de mayor a menor o viceversa.
Análisis de Medallas Totales por País: Obtener un dataframe que contenga sólo los países que ganaron más de 10 medallas en total.
Una vez que hayas realizado estos pasos, HAZ UN PDF, que contenga las respuestas a los incisos planteados.

In [1]:
import numpy as np
import pandas as pd

1. Creación del DataFrame a partir de los datos de medallas.csv

In [11]:
ruta = "C:/medallas.csv"
df = pd.read_csv(ruta)

df

     Oro  Plata  Bronce  Total          Pais
0    NaN    1.0     2.0      3     Argentina
1    NaN    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    NaN    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   NaN    1.0     NaN      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    NaN     2.0      5    Uzbekistan
92   1.0    3.0     NaN      4     Venezuela

[93 rows x 5 columns]

In [ ]:
2. Observaciones de los datos usando Pandas.

In [12]:
df.info() #Aqui podemos ver como en las 3 tipos de medallas existen campos nulos
#Y descartamos que el total y el pais contengan datos que son nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [13]:
df.head()

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [14]:
df.isnull() #Aqui visualizamos de una diferente manera los datos nulos, donde hay un True hay un nulo

      Oro  Plata  Bronce  Total   Pais
0    True  False   False  False  False
1    True  False   False  False  False
2   False  False   False  False  False
3   False  False   False  False  False
4    True  False   False  False  False
..    ...    ...     ...    ...    ...
88   True  False    True  False  False
89  False  False   False  False  False
90  False  False   False  False  False
91  False   True   False  False  False
92  False  False    True  False  False

[93 rows x 5 columns]

In [15]:
df.isnull().sum() #Sumamos la cantidad de nulos que hay en cada medalla

Oro       28
Plata     24
Bronce    17
Total      0
Pais       0
dtype: int64

In [16]:
#Aqui vamos a hacer el cambio de valor para los nulos, rellenaremos esos espacios vacíos específicamente con el   
#numero cero. Si un país tiene un dato faltante en la columna "Bronce" por ejemplo, significa que no ganó ninguna.
valores_nuevos = {"Oro":0, 
                  "Plata":0,
                  "Bronce":0
                 }
df_rellenados = df.fillna(valores_nuevos)
df = df_rellenados

#Y mostraremos el resultado final de nuestro dataframe modificado
df

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [30]:
#Aqui estoy haciendo el cambio de tipo de dato de cada una de las medallas a entero, porque no se puede
#tener 1.5 medallas.
df["Oro"] = df["Oro"].astype(int)
df["Plata"] = df["Plata"].astype(int)
df["Bronce"] = df["Bronce"].astype(int)
df

    Oro  Plata  Bronce  Total          Pais
0     0      1       2      3     Argentina
1     0      2       2      4       Armenia
2    17      7      22     46     Australia
3     1      1       5      7       Austria
4     0      3       4      7    Azerbaijan
..  ...    ...     ...    ...           ...
88    0      1       0      1  Turkmenistan
89    2      1       1      4        Uganda
90    1      6      12     19       Ukraine
91    3      0       2      5    Uzbekistan
92    1      3       0      4     Venezuela

[93 rows x 5 columns]

In [ ]:
3. Top 3 de paises con mas medallas olimpicas

In [31]:
#df.sort_values(by='NombreDeLaColumna', ascending=False) sintaxis de la funcion utilizada
#by se usa para pasar el nombre de la columna (como string) a usar como referencia para ordenar. 
#ascending se usa para recibir un valor booleano (True o False). Por defecto viene en True (ascendente, es decir, 
#del número más pequeño al más grande).
df.sort_values(by='Total', ascending = False).head(3)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC

4. Los 10 paíases que tienen más de 10 medallas olimpicas.

In [33]:
#Sintaxis DataFrame[ DataFrame['NombreDeLaColumna'] > ValorNumerico ]
df[df['Total'] > 10]

    Oro  Plata  Bronce  Total                        Pais
2    17      7      22     46                   Australia
11    7      6       8     21                      Brazil
14    7      6      11     24                      Canada
15    2      4       6     12              Chinese Taipei
19    7      3       5     15                        Cuba
20    4      4       3     11              Czech Republic
21    3      4       4     11                     Denmark
25   39     41      33    113   Estados Unidos de America
30    1     12      11     33                      France
32    1     11      16     37                     Germany
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
60    1     12      14     36                 Netherlands
66    4      5       5     14                      Poland
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
81    3      8       6     17                       Spain
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
90    1      6      12     19                     Ukraine